version: '3'
services:
  python-service:
    build:
      context: ./python-app
      dockerfile: Dockerfile
    container_name: my-python-container

  java-service:
    build:
      context: ./java-app
      dockerfile: Dockerfile
    container_name: my-java-container

  c-service:
    build:
      context: ./c-app
      dockerfile: Dockerfile.c
    container_name: my-c-container

  cpp-service:
    build:
      context: ./cpp-app
      dockerfile: Dockerfile.cpp
    container_name: my-cpp-container
